# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Glitch_PUF.xdc

# IP: new/LBlockUART/PUF/PLL/PLL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] -quiet
